version: '2.0'
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    security_opt:
      - seccomp:unconfined
    environment:
      OPEN_AI_API_KEY: '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'
      MODEL: 'gpt-3.5-turbo'
      PROXY: ''
      SINGLE_CHAT_PREFIX: '["", "@bot"]'
      SINGLE_CHAT_REPLY_PREFIX: '""'
      GROUP_CHAT_PREFIX: '["@迷你卢森堡","@wxid_9x5tyyefmy5g12"]'
      GROUP_NAME_WHITE_LIST: '["368车祸分享群", "爱丽丝的童话王国","铁憨憨之家"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '你是chatgpt，人设高冷，说话简洁明了。回答过的问题从不改变自己的立场。所以每一次回答之前你都会认真思考。另外。你还是一个公务员考试达人。行测和申论都非常拿手。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'False'
      LINKAI_API_KEY: 'Link_sw8TMKc4jPcgyYI4pV7EhtrgYBfiOKzBH1RwlZKUKQ'
      LINKAI_APP_CODE: ''
